---
# used for running tests
name: tests

on:
  push:
    branches: [main, fixes]
  pull_request:
    branches: [main]

jobs:
  pre_commit_checks:
    runs-on: ubuntu-22.04
    steps:
      # checks out the repo
      - uses: actions/checkout@v4
      # run pre-commit
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      # enable testing on Qt on linux
      - name: Install Linux libraries
        if: runner.os == 'Linux'
      - run: |
            sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 \
              libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 \
              libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 x11-utils
      - uses: pre-commit/action@v3.0.1
  run_tests:
    strategy:
      matrix:
        python_version: ["3.11", "3.12"]
        os: [ubuntu-22.04, macos-13]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      # enable testing on Qt on linux
      - name: Install Linux libraries
        if: runner.os == 'Linux'
      - run: |
            sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 \
              libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 \
              libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 x11-utils
      - name: Run pytest
        run: uv run pytest
