---
# used for running tests
name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre_commit_checks:
    runs-on: ubuntu-22.04
    steps:
      # checks out the repo
      - uses: actions/checkout@v4
      # run pre-commit
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - uses: pre-commit/action@v3.0.1
  run_tests:
    strategy:
      matrix:
        python_version: ["3.11", "3.12"]
        os: [ubuntu-22.04, macos-13]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install QT dependencies for Ubuntu
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: tlambert03/setup-qt-libs@v1
      - name: Display configuration for Ubuntu
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        # referenced from
        # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html
        run: |
          /sbin/start-stop-daemon \
          --start --quiet --pidfile \
          /tmp/custom_xvfb_99.pid --make-pidfile \
          --background --exec /usr/bin/Xvfb \
          -- :99 -screen 0 1920x1200x24 -ac +extension GLX
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Run pytest
        run: uv run --frozen pytest
